{
	"version": 1717252758,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/hero-sheet0.png",
		"images/hero-sheet1.png",
		"images/hero-sheet2.png",
		"images/hero-sheet3.png",
		"images/box-sheet0.png",
		"images/box-sheet1.png",
		"images/podarok-sheet0.png",
		"images/podarok-sheet1.png",
		"images/sputnik-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite6-sheet1.png",
		"images/tornado-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/whitegirl-sheet0.png",
		"images/whitegirl-sheet1.png",
		"images/flore-sheet0.png",
		"images/backlajan-sheet0.png",
		"images/backlajan-sheet1.png",
		"images/sprite8-sheet0.png",
		"images/sprite8-sheet1.png",
		"images/sprite9-sheet0.png",
		"images/medic-sheet0.png",
		"images/uidamagehealth-sheet0.png",
		"images/uidamagehealth-sheet1.png",
		"images/uidamagehealth-sheet2.png",
		"images/vedma-sheet0.png",
		"images/magicbulet-sheet0.png",
		"images/radiobullet-sheet0.png",
		"images/radiobullet-sheet1.png",
		"images/uipanelhab-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/gamepad-sheet0.png",
		"images/gamepad-sheet1.png",
		"images/klizma-sheet0.png",
		"images/klizma-sheet1.png",
		"images/feia-sheet0.png",
		"images/feia-sheet1.png",
		"images/feia-sheet2.png",
		"images/bluefeia-sheet0.png",
		"images/pomidormutant-sheet0.png",
		"images/mutant-sheet0.png",
		"images/maska-sheet0.png",
		"images/citypol-sheet0.png",
		"images/zaika-sheet0.png",
		"images/zaika-sheet1.png",
		"images/dolboiasher-sheet0.png",
		"images/dolboiasher-sheet1.png",
		"images/dolboiasher-sheet2.png",
		"images/godzill-sheet0.png",
		"images/portfel-sheet0.png",
		"images/licichka-sheet0.png",
		"images/licichka-sheet1.png",
		"images/sprite5-sheet0.png",
		"images/uibuttonrigthsprite-sheet0.png",
		"images/uibuttonrigthsprite-sheet1.png",
		"images/uibuttonupsprite-sheet0.png",
		"images/uibuttonupsprite-sheet1.png",
		"images/uibuttondownsprite-sheet0.png",
		"images/uibuttondownsprite-sheet1.png",
		"images/uibuttonleftsprite-sheet0.png",
		"images/uibuttonleftsprite-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/sprite11-sheet0.png",
		"images/sprite11-sheet1.png",
		"images/sprite11-sheet2.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite13-sheet1.png",
		"images/sprite16-sheet0.png",
		"images/sprite16-sheet1.png",
		"images/crazymorkovka-sheet0.png",
		"images/crazymorkovka-sheet1.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite19-sheet1.png",
		"images/dobraiavedma-sheet0.png",
		"images/sprite36-sheet0.png",
		"images/sprite36-sheet1.png",
		"images/kniga-sheet0.png",
		"images/kniga-sheet1.png",
		"images/openkniga-sheet0.png",
		"images/sprite41-sheet0.png",
		"images/sprite42-sheet0.png",
		"images/bookhistory-sheet0.png",
		"images/sprite44-sheet0.png",
		"images/sprite44-sheet1.png",
		"images/sprite44-sheet2.png",
		"images/sprite44-sheet3.png",
		"images/sprite44-sheet4.png",
		"images/sprite44-sheet5.png",
		"images/sprite48-sheet0.png",
		"images/sprite48-sheet1.png",
		"images/sprite48-sheet2.png",
		"images/sox-sheet0.png",
		"images/tornadokidaushi2prizrak-sheet0.png",
		"images/sprite49-sheet0.png",
		"images/sprite49-sheet1.png",
		"images/morkovkolet-sheet0.png",
		"images/morkovkolet-sheet1.png",
		"images/bossturet-sheet0.png",
		"images/volniantivirusa-sheet0.png",
		"images/sprite52-sheet0.png",
		"images/uipanelhabmorkovki-sheet0.png",
		"images/nagradaprosheligru-sheet0.png",
		"images/nagradavilechilkomp-sheet0.png",
		"images/sprite54-sheet0.png",
		"images/chip-sheet0.png",
		"images/chip-sheet1.png",
		"images/chip-sheet2.png",
		"images/viruspc-sheet0.png",
		"images/activationppppp-sheet0.png",
		"images/tiledbackground2.png",
		"images/sprite56-sheet0.png",
		"images/aptechka-sheet0.png",
		"images/aptechka-sheet1.png",
		"images/extrenaiajizn-sheet0.png",
		"images/popastsudavminigame2-sheet0.png",
		"images/doljenupast-sheet0.png",
		"images/sprite57-sheet0.png",
		"images/sprite57-sheet1.png",
		"images/sprite59-sheet0.png",
		"images/fightingbeliaska-sheet0.png",
		"images/fightingbeliaska-sheet1.png",
		"images/fightingbeliaska-sheet2.png",
		"images/gitara-sheet0.png",
		"images/gitara-sheet1.png",
		"images/sprite61-sheet0.png",
		"images/uibaklajan-sheet0.png",
		"images/beliaskalazer-sheet0.png",
		"images/sprite62-sheet0.png",
		"images/beliaskazahvachena-sheet0.png",
		"images/beliaskazahvachena-sheet1.png",
		"images/uirampage-sheet0.png",
		"images/uibaklrampage-sheet0.png",
		"images/surpizezone4-sheet0.png",
		"images/ynichtojiteliashikov-sheet0.png",
		"images/zonasvobodi-sheet0.png",
		"images/osvoboditel-sheet0.png",
		"images/nagradapobedilibaklajana-sheet0.png",
		"images/uivirus-sheet0.png",
		"images/secretbox-sheet0.png",
		"images/secretbox-sheet1.png",
		"images/secretbox-sheet2.png",
		"media/bonus.m4a",
		"media/bonus.ogg",
		"media/podarok.m4a",
		"media/podarok.ogg",
		"media/krik-lisy [high quality].m4a",
		"media/krik-lisy [high quality].ogg",
		"media/bluenude.m4a",
		"media/bluenude.ogg",
		"media/vozmushenie girl [high quality].m4a",
		"media/vozmushenie girl [high quality].ogg",
		"media/vistreligroka [high quality].m4a",
		"media/vistreligroka [high quality].ogg",
		"media/vilechilsia.m4a",
		"media/vilechilsia.ogg",
		"media/mutaciapomidora [high quality].m4a",
		"media/mutaciapomidora [high quality].ogg",
		"media/razrushenie-avariya-32307.m4a",
		"media/razrushenie-avariya-32307.ogg",
		"media/razrushayuschee-padenie-staryih-gnilyih-dosok.m4a",
		"media/razrushayuschee-padenie-staryih-gnilyih-dosok.ogg",
		"media/dajenskii.m4a",
		"media/dajenskii.ogg",
		"media/girlsmeetsia.m4a",
		"media/girlsmeetsia.ogg",
		"media/girlvotspasibo.m4a",
		"media/girlvotspasibo.ogg",
		"media/prichudlivyy-zvuk-gubami-brrrrr.m4a",
		"media/prichudlivyy-zvuk-gubami-brrrrr.ogg",
		"media/zvykmorkovki [high quality].m4a",
		"media/zvykmorkovki [high quality].ogg",
		"media/zvuk-ups-23 [high quality].m4a",
		"media/zvuk-ups-23 [high quality].ogg",
		"media/two-girls-laughing-02 [high quality].m4a",
		"media/two-girls-laughing-02 [high quality].ogg",
		"media/fistful-of-frags-victory [high quality].m4a",
		"media/fistful-of-frags-victory [high quality].ogg",
		"media/den-pobedy-z_uk-1 [high quality].m4a",
		"media/den-pobedy-z_uk-1 [high quality].ogg",
		"media/zvukvolniantivirusa [high quality].m4a",
		"media/zvukvolniantivirusa [high quality].ogg",
		"media/virusvilechen [high quality].m4a",
		"media/virusvilechen [high quality].ogg",
		"media/antivirusnedoletel [high quality].m4a",
		"media/antivirusnedoletel [high quality].ogg",
		"media/nosokrazrushen [high quality].m4a",
		"media/nosokrazrushen [high quality].ogg",
		"media/zvykvzmaha2.m4a",
		"media/zvykvzmaha2.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/ydarbaklajana.m4a",
		"media/ydarbaklajana.ogg",
		"media/lazerbeliaski [high quality].m4a",
		"media/lazerbeliaski [high quality].ogg",
		"media/lazerbeliaski2 [high quality].m4a",
		"media/lazerbeliaski2 [high quality].ogg",
		"media/dliacombobacklajana [high quality].m4a",
		"media/dliacombobacklajana [high quality].ogg",
		"media/stolknovenie-razrusheniya [high quality].m4a",
		"media/stolknovenie-razrusheniya [high quality].ogg",
		"media/nosokrazrushen222 [high quality].m4a",
		"media/nosokrazrushen222 [high quality].ogg",
		"media/backgroundmuzik.m4a",
		"media/backgroundmuzik.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}